/*
Purpose:
Exploratory Data Analysis (EDA) of the DataWarehouseAnalytics data warehouse.
This script profiles the customer, product, and sales domains by examining
metadata, validating data coverage, calculating core business KPIs, and
identifying top/bottom performing products and customers.
*/

-- 13-06-2026
USE DataWarehouseAnalytics

-- Explore all tables available in the database
SELECT *
FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns available in the database
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS

-- Explore all columns in the customer dimension
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- List all customer countries
SELECT DISTINCT country
FROM gold.dim_customers

-- Review product hierarchy and catalog structure
SELECT DISTINCT
    category,
    subcategory,
    product_name
FROM gold.dim_products
ORDER BY 1,2,3

-- Determine available sales history period
SELECT
    MIN(order_date) AS FirstOrderDate,
    MAX(order_date) AS LastOrderDate,
    DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years,
    DATEDIFF(month, MIN(order_date), MAX(order_date)) AS order_range_months
FROM gold.fact_sales

-- Identify youngest and oldest customers based on birthdate
SELECT
    MIN(birthdate) AS oldest_birthdate,
    DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_Age,
    MAX(birthdate) AS youngest_birthdate,
    DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_Age
FROM gold.dim_customers

-- Total revenue generated
SELECT
    SUM(sales_amount) AS total_sales
FROM gold.fact_sales

-- Total units sold
SELECT
    SUM(quantity) AS items_quantity
FROM gold.fact_sales

-- Average transaction unit price
SELECT
    AVG(price) AS avg_price
FROM gold.fact_sales

-- Compare total order rows versus unique orders
SELECT
    COUNT(order_number) AS total_orders,
    COUNT(DISTINCT order_number) AS distinct_total_orders
FROM gold.fact_sales

-- Compare total product rows versus unique products
SELECT
    COUNT(product_key) AS total_products,
    COUNT(DISTINCT product_key) AS distinct_total_products
FROM gold.dim_products

-- Compare total customer rows versus unique customers
SELECT
    COUNT(customer_key) AS total_customers,
    COUNT(DISTINCT customer_key) AS distinct_total_customers
FROM gold.dim_customers

-- Customers who have placed at least one order
SELECT
    COUNT(DISTINCT customer_key) AS total_customers
FROM gold.fact_sales

-- Consolidated KPI report
SELECT
    'Total Sales' AS measure_name,
    SUM(sales_amount) AS measure_value
FROM gold.fact_sales

UNION ALL

SELECT
    'Total Quantity' AS measure_name,
    SUM(quantity)
FROM gold.fact_sales

UNION ALL

SELECT
    'Average Price' AS measure_name,
    AVG(price)
FROM gold.fact_sales

UNION ALL

SELECT
    'Total Nr. Orders' AS measure_name,
    COUNT(DISTINCT order_number)
FROM gold.fact_sales

UNION ALL

SELECT
    'Total Nr. Products' AS measure_name,
    COUNT(product_key)
FROM gold.dim_products

UNION ALL

SELECT
    'Total Nr. Customers' AS measure_name,
    COUNT(customer_key)
FROM gold.dim_customers

-- Customer distribution by country
SELECT
    country,
    COUNT(customer_id) AS total_customers_countries
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers_countries DESC

-- Customer distribution by gender
SELECT
    gender,
    COUNT(customer_id) AS total_customers_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers_gender DESC

-- Product distribution by category
SELECT
    category,
    COUNT(product_key) AS total_products_cat
FROM gold.dim_products
GROUP BY category
ORDER BY total_products_cat DESC

-- 14-06-2026

-- Average product cost by category
SELECT
    category,
    AVG(cost) AS Average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY Average_costs DESC

-- Revenue generated by product category
SELECT
    p.category,
    SUM(f.sales_amount) AS tatal_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY tatal_revenue DESC

-- Revenue generated by customer
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS tatal_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY tatal_revenue DESC

-- Quantity sold by customer country
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC

-- Top 5 products by revenue
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- Bottom 5 products by revenue
SELECT TOP 5
    p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
    ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC

-- Alternative bottom-5 ranking using a window function
SELECT *
FROM (
    SELECT
        p.product_name,
        SUM(f.sales_amount) AS total_revenue,
        ROW_NUMBER() OVER (
            ORDER BY SUM(f.sales_amount)
        ) AS rank_products
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON f.product_key = p.product_key
    GROUP BY p.product_name
) t
WHERE rank_products <= 5

-- Top 10 customers by revenue
SELECT TOP 10
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS tatal_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY tatal_revenue DESC

-- 3 Customers with the fewest unique orders
SELECT TOP 3
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT f.order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders